baseURL = "https://mitbitcoinexpo.org/"
languageCode = "en-us"
title = "MIT Bitcoin Expo 2022"
themesDir = "themes"
staticDir = "static"
theme = "hugo-whisper-theme"

disableKinds = ["taxonomy", "taxonomyTerm"]

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[markup.goldmark.renderer]
unsafe = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30


[params]
  google_analytics_id= "UA-159043754-1"
  homepage_button_link = '/flashback_2021'
  homepage_button_text = '2021 Expo'
  homepage_button_link2 = '/flashback_2020'
  homepage_button_text2 = '2020 Expo'
  homepage_intro = ''
  homepage_image = './images/btc-live.jpg'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "MIT Bitcoin Expo 2022"
    meta_og_title = "MIT Bitcoin Expo 2022"
    meta_og_type = "website"

  [params.logo]
      mobile = "/images/logo.png"
      standard  = "/images/logo.png"
