from tornado import template
loader = template.Loader(".")
speakers = [("""./headshots/Gavin.png""",
"""Gavin Andresen""",
"""Core Developer, Bitcoin""",
"""Gavin is the Chief Scientist at the Bitcoin Foundation and one of the original developers of the Bitcoin protocol. His wife allegedly no longer calls Bitcoin his "make-believe money project."""),
("""./headshots/Charlie.png""",
"""Charlie Lee""",
"""Creator, Litecoin""",
"""Charlie is the creator of Litecoin, the most popular alternative to Bitcoin. He is currently at Coinbase leading the product team. Prior to that, he spent 6 years at Google. Charlie is also an MIT alum."""),
("""./headshots/Peter.png""",
"""Peter Todd""",
"""Core Developer, Bitcoin""",
"""Peter is currently working on treechains, with permissionless development, decentralized mining, and scalability. Prior to this, he was Chief Scientist of Dark Wallet and MasterCoin."""),
("""./headshots/Jeremy.png""",
"""Jeremy Allaire""",
"""CEO, Circle""",
"""Jeremy is the CEO and cofounder of Circle Internet Financial and Chairman at Brightcove, which he also founded. His roles prior to Circle include CEO of Brightcove and CTO of Macromedia."""),
("""./headshots/Juthica.png""",
"""Juthica Chou""",
"""President, LedgerX""",
"""Juthica is the current co-founder and president of LedgerX. Prior to her current role, she specialized in algorithmic trading at Goldman Sachs for 7 years as a derivatives trader. Juthica is also an MIT alum."""),
("""./headshots/Joshua.png""",
"""Joshua Lim""",
"""Treasury &amp; Trading, Circle""",
"""Joshua is the current head of treasury and trading operations at Circle. Prior to that, he worked as an associate at Goldman Sachs for five years as a trader specializing in exotic derivatives. Joshua is an MIT alum."""),
("""./headshots/Constance.png""",
"""Constance Choi""",
"""Principal, Seven Advisory""",
"""Constance specializes in bridging the gap between tech companies and complex regulatory frameworks. Prior to Seven, she founded Kraken Exchange and worked there as the Chief Compliance Officer."""),
("""./headshots/Melanie.png""",
"""Melanie Shapiro""",
"""CEO, CryptoLabs""",
"""Melanie is currently the founder and CEO of CryptoLabs, where she is working on Case, a secure Bitcoin wallet. She also has a PhD in Consumer Behaviour from Henley Business School."""),
("""./headshots/Arvind.png""",
"""Arvind Narayanan""",
"""Professor, Princeton""",
"""Arvind is currently an assistant professor at Princeton, where his major research areas are web privacy, big data, and bitcoin & other cryptocurrencies. He is most known for his research in data privacy."""),
("""./headshots/Andy.png""",
"""Andy Ofiesh""",
"""Developer, Armory""",
"""Andy is currently one of the lead developers at Armory Technologies. He has masters degrees in software engineering and computer science, and is also a standup comic in Boston."""),
("""./headshots/Adam.png""",
"""Adam Ludwin""",
"""Founder, Chain""",
"""Adam is a co-founder of Chain, a way for developers to fully take advantage of the security and power of the bitcoin ecosystem by abstracting away the superfluos details of the blockchain."""),
("""./headshots/Jerry.png""",
"""Jerry Brito""",
"""Executive Director, Coin Center""",
"""Jerry Brito is executive director of Coin Center, a nonprofit research and advocacy center focused on the public policy issues facing cryptocurrency technologies such as Bitcoin."""),
("""./headshots/Dan.png""",
"""Dan Elitzer""",
"""MIT Bitcoin Project""",
"""Dan founded the MIT Bitcoin Club and is a second year MBA Candidate at MIT Sloan. Prior to attending MIT, Dan worked at Grameen Foundation, where he became interested in Bitcoin."""),
("""./headshots/Sam.png""",
"""Sam Udotong""",
"""Founder, Fireflies""",
"""Sam is a junior at MIT studying aerospace engineering. He participated in the summer-long MIT BitComp and his app Fireflies (an on-demand p2p delivery platform) won the Awesome award."""),
("""./headshots/Alan.png""",
"""Alan Reiner""",
"""CEO, Armory""",
"""Alan is the core developer of the Armory Bitcoin Client, one of the first wallets to make cold storage accessible through a user interface. He first came on to the bitcoin scene as a miner."""),
("""./headshots/Christian.png""",
"""Christian Catalini""",
"""Professor, MIT Sloan""",
"""Christian is currently a professor at MIT Sloan where he focuses the brunt of his research on the economics of innovation, entrepreneurship and scientific productivity. He is one of the lead researchers on the MIT Bitcoin Project."""),
("""./headshots/Jonathan.png""",
"""Jonathan Harvey-Buschel""",
"""President, MIT Bitcoin Club""",
"""Jonathan is the current president of the MIT Bitcoin Club, and a freshman studying EE at MIT. He entered the world of cryptocurrency via dogecoin mining, and is currently working on BitVend, a vending machine platform that accepts Bitcoin."""),
("""./headshots/Rubin.png""",
"""Jeremy Rubin""",
"""MIT Bitcoin Project""",
"""Jeremy is an EECS junior at MIT. He came onto the bitcoin scene with Tidbit, a system to replace web ads with cryptocurrency mining (currently fighting NJ). Jeremy is also a founder of the MIT Bitcoin Project."""),
("""./headshots/Jinglan.png""",
"""Jinglan Wang""",
"""President, Wellesley Bitcoin""",
"""Jing is currently a junior at Wellesley College, studying studio art and CS. She is working on developing a cryptocurrency course at Wellesley. She also writes and illustrates comics on Bitcoin and cryptography.""")]
sponsors = [("""./sponsors/circle.png""","Circle"),
("""./sponsors/chain.png""","Chain")]
with open("index.html", "w") as f:
    f.write(loader.load("index.tmpl").generate(speakers=speakers,sponsors=sponsors))
